---

- name: Firewall configuration for ubuntu
  hosts: ubuntu
  become: true

  tasks:

    - name: Enable UFW and deny incoming traffic
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming

    - name: Allow SSH
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Check if Public key of sysadmin is in autorized_key
      ansible.posix.authorized_key:
        user: sysadmin
        state: present
        key: "{{ lookup('file', '/home/sysadmin/.ssh/id_rsa.pub') }}"

    - name: Remove login with password in SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
      notify: Restart SSH

  handlers:
    
    - name: Restart SSH
      ansible.builtin.systemd.service:
        name: ssh
        state: restarted


