---
- name: Deploy Apache web server on Centos
  hosts: centos
  cebome: true

  tasks:

    - name: Install apache (httpd)
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start httpd service
      ansible.builtin.systemd_service:
        name: httpd
        state: started
        enabled: true

    - name: Add service httpd to firewalld
      ansible.posix.firewalld:
        service: "{{ item }}" 
        state: enabled
        permanent: true
        immediate: true
      loop: [http, https]

